engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: false
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- "config/"
- "db/"
- "spec/"
- "/log/*"
- "/config/secrets.yml"
- "/config/local_env.yml"
- "/.bundle"
- "/.bundle"
