web:
  build: .
  command: puma
  ports:
    - "9292:9292"
  links:
    - db
    - redis
  volumes:
    - .:/ur_secured
  stdin_open: true
  tty: true

sidekiq:
  build: .
  volumes:
    - .:/ur_secured
  command: bundle exec sidekiq
  links:
    - db
    - redis
  env_file:
    - .env
db:
  image: postgres

redis:
  image: redis