development: &default
  adapter: postgresql
  encoding: unicode
  database: ur_secured_development
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: db

test:
  <<: *default
  database: ur_secured_test
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>